### ISSUE TITLE
mini_racer makes middleman build stuck

### ISSUE THREAD

**Issue by brodock** [rubyjs/mini_racer#159] opened 2020-03-01 17:52 UTC
This was reported first in https://github.com/middleman/middleman/issues/2254

To reproduce, you need a middleman setup with the following configuration:

```
configure :build do
  # Minify Javascript on build
  activate :minify_javascript
end
```

There seems to be some issue with using it together with parallel. 

This is what I could get from running `rbspy snapshot` against a stuck build:

```
<main> - /Users/brodock/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24
<c function> - unknown:0
<main> - /Users/brodock/.rvm/gems/ruby-2.6.5/bin/middleman:26
<c function> - unknown:0
<top (required)> - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-cli-4.3.5/bin/middleman:70
start - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/base.rb:476
dispatch - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:388
invoke_command - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:128
run - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:37
block in register - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:40
invoke - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:118
dispatch - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/group.rb:234
invoke_all - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:134
<c function> - unknown:0
<c function> - unknown:0
block in invoke_all - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:133
invoke_command - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:128
run - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:37
build - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:97
instrument - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:22
instrument - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:168
block in build - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-cli-4.3.5/lib/middleman-cli/build.rb:96
block in redefine_method - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_handler.rb:153
call_with - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/call_with.rb:95
send_to - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_reference.rb:44
run! - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:87
instrument - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/util.rb:22
instrument - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:168
block in run! - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:72
block in redefine_method - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_handler.rb:153
call_with - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/call_with.rb:95
send_to - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_reference.rb:44
output_files - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:132
block in redefine_method - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_handler.rb:153
call_with - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/call_with.rb:95
send_to - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/contracts-0.13.0/lib/contracts/method_reference.rb:44
output_resources - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/middleman-core-4.3.5/lib/middleman-core/builder.rb:160
map - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/parallel-1.18.0/lib/parallel.rb:282
work_in_processes - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/parallel-1.18.0/lib/parallel.rb:418
create_workers - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/parallel-1.18.0/lib/parallel.rb:438
<c function> - unknown:0
<c function> - unknown:0
block in create_workers - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/parallel-1.18.0/lib/parallel.rb:436
worker - /Users/brodock/.rvm/gems/ruby-2.6.5/gems/parallel-1.18.0/lib/parallel.rb:464
<c function> - unknown:0
```

**Comment by SamSaffron** [comment] 2020-03-02 05:11
Oh we already have locking here: 

https://github.com/SamSaffron/mini_racer/blob/b457294cb629cdc67736fb00ab9d25c834f46c67/lib/mini_racer.rb#L212-L216

So my guess is `ruby_executable_hooks` which is provided to mini racer is triggering a deadlock. 

What is the hook it is calling?

**Comment by tisba** [comment] 2020-04-05 20:00
We are having issues with the `parallel` gem as well. mini_racer `0.2.7` to `0.2.9` causes segfaults with our test suite. For some reason `0.2.6` seems to be fine.

Not sure if this related, but I stumbled across this issue and saw that the `parallel` gem is used.

**Comment by SamSaffron** [comment] 2020-11-11 21:58
so sorry, closing this as a dupe of: #170

**Closed by SamSaffron** 2020-11-11 21:58 UTC
